name: publish

on:
    release:
        types: [created]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout sources
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.6"

            - name: Install dependencies
              run: |
                  pip install -r requirements.txt -r requirements-dev.txt

            - name: Minimal test
              run: |
                  flickr2kml --help
            
            - name: Publish to PyPi
              env:
                  TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
                  TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
              run: |
                  python setup.py sdist bdist_wheel
                  twine upload dist/*